version: '2'
services:
  vulnwhisp_es1:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.2
    container_name: vulnwhisp_es1
    environment:
      - cluster.name=vulnwhisperer
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 1g
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    ports:
      - 19200:9200
    networks:
      - esnet
  vulnwhisp_ks1:
    image: docker.elastic.co/kibana/kibana:5.6.2
    environment:
      SERVER_NAME: vulnwhisp_ks1
      ELASTICSEARCH_URL: http://vulnwhisp_es1:9200
    ports:
      - 15601:5601
    networks:
      - esnet
  vulnwhisp_ls1:
    image: docker.elastic.co/logstash/logstash:5.6.2
    networks:
      - esnet

  vulnwhisp_openvas1:
    image: mikesplain/openvas:9
    ports:
      - 443:443
      - 9390:9390
    environment:
       OV_PASSWORD: admin
    networks:
      - esnet

  vulnwhisp_vulnwhisperer1:
    image: danitfk/vulnwhisperer:1
    environment:
       OV_PASSWORD: admin
    networks:
      - esnet

volumes:
  esdata1:
    driver: local

networks:
  esnet:
